name: Build Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: NodeScriptLang/github-actions/.github/workflows/ci-build.yaml@main
    with:
      image: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-adapter-curl
      file: Dockerfile
    secrets:
      REGISTRY_SECRET: ${{ secrets.GCP_REGISTRY_ACCESS }}
